name: outilsplus_v2
version: '${version}'
main: outilsplus_v2.outilsplus_v2.outilsplus_v2
api-version: 1.19
commands:
    veinminer:
        description: Donne une pioche pour le veinmining avec un NBT Tag précis
        usage: /<command>
        permission: outilsplusv2.veinminer
    timberaxe:
        description: Donne une hache pour le cassage en un coup  des arbres avec un NBT Tag précis
        usage: /<command>
        permission: outilsplusv2.timberaxe
    houefarmer:
        description: Donne une houe pour l'utilisation en 3x3 en un coup des blocks grace a un NBT Tag précis
        usage: /<command>
        permission: outilsplusv2.houefarmer