name: outilsplus_v2
version: '${version}'
main: outilsplus_v2.outilsplus_v2.outilsplus_v2
api-version: 1.19
commands:
    giveitem:
        description: Donne un objet avec NBT Tag précis
        usage: /<command>
        permission: op
